sonar.projectKey=opensalestax-opencart
sonar.projectName=opensalestax-opencart
sonar.projectVersion=0.1.0
sonar.sources=src,extension/upload
sonar.tests=tests
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/vendor/**,**/build/**,**/dist/**,**/coverage*/**,extension/upload/system/library/opensalestax/vendor/**
sonar.test.inclusions=tests/**/*Test.php
sonar.host.url=http://10.32.161.205:9000
